### ISSUE TITLE
Real time data

### ISSUE THREAD

**Issue by MadsN94** [nordleif/CSMarkdown#9]
SignalR

**Comment by Axelfarm** [comment]
http://embed.plnkr.co/TDQUAF/
Under setInterval bliver der lavet et push til data.

**Comment by Axelfarm** [comment]
Inspiration:
http://plnkr.co/edit/w5cakqUdzIVLq7GlSdcy?p=preview

og skift koden i script.js med:
// Code goes here

/_var testdata = stream_layers(7,10+Math.random()_100,.1).map(function(data, i) {
  return {
    key: 'Stream' + i,
    values: data.map(function(a){a.y = a.y \* (i <= 1 ? -1 : 1); return a})
  };
});

testdata[0].type = "area";
testdata[0].yAxis = 1;
testdata[1].type = "area";
testdata[1].yAxis = 1;
testdata[2].type = "line";
testdata[2].yAxis = 1;
testdata[3].type = "line";
testdata[3].yAxis = 2;
testdata[4].type = "bar";
testdata[4].yAxis = 2;
testdata[5].type = "bar";
testdata[5].yAxis = 2;
testdata[6].type = "bar";
testdata[6].yAxis = 2; */

var data = [
    {
        "key": "FCA",
        "values": [
             {
                "x": 1435689000000,
                "y": 306402556.66
            },
            {
                "x":  1435775400000,
                "y": 275762300.99
            },
             {
                "x": 1435861800000,
                "y": 248186070.89
            },
            {
                "x": 1435948200000,
                "y": 223367463.81
            },
              {
                "x":1436034600000,
                "y": 109056415.38
            },
            {
                "x": 1436121000000,
                "y": 111996205.69
            },
             {
                "x": 1436207400000,
                "y": 13195826.26
            }

```
    ],
    "type": "line",
    "yAxis": 1
},
{
    "key": "Gross Deficit",
    "values": [
        {
            "x": 1435689000000,
            "y": 7448699.91
        },
        {
            "x": 1435775400000,
            "y": 8193569.90
        },
         {
            "x": 1435861800000,
            "y": 9012926.89
        },
        {
            "x": 1435948200000,
            "y": 9914219.58
        },
          {
            "x": 1436034600000,
            "y": 119056415.38
        },
        {
            "x": 1436121000000,
            "y": 11996205.69
        },
         {
            "x": 1436207400000,
            "y": 13195826.26
        }
    ],
    "type": "line",
    "yAxis": 2
}
```

]

var chart;
nv.addGraph(function() {
  chart = nv.models.multiChart()
  .margin({top: 30, right: 60, bottom: 50, left: 70})
  .color(d3.scale.category10().range());

  chart.xAxis.tickFormat(function(d) {
              return d3.time.format('%d/%m/%Y')(new Date(d))
             });
  chart.yAxis1.tickFormat(d3.format(',.0f'));
  chart.yAxis2.tickFormat(d3.format(',.1f'));

  chart.lines1.duration(500);
  chart.lines2.duration(0);

  d3.select('#chart1 svg')
  .datum(data)
  .transition().duration(500).call(chart);

  return chart;
});

var x = 2;
var run = true;
setInterval(function(){
    if (!run) return;
    var spike = (Math.random() > 0.95) ? 10: 1;
    data[0].values.push({
        x: x,
        y: Math.random() \* spike
    });
    var spike2 = (Math.random() > 0.95) ? 10: 1;
    data[1].values.push({
        x: x,
        y: Math.random() \* spike
    });
    if (data[0].values.length > 20) {
        data[0].values.shift();
        data[1].values.shift();

```
}
x++;
chart.update();
```

}, 500);

Med fokus på delene med data[].values.push og data[].values.shift();
Hvor push jo tilføjer til datasættet, og shift billedligt fjerner den første (den mest til venstre på grafen)
Og der skal kaldes en chart.update();.

Dette kan bruges til når portalen skal laves.

**Comment by Axelfarm** [comment]
https://code.msdn.microsoft.com/Broadcast-Real-time-SQL-69dd9fcc

Brug af SignalR til real time data fra SQL
